(function(g){var window=this;'use strict';var N2=function(a){a.publish("cardstatechange",a.Nl()&&a.Wp()?1:0)},O2=function(a,b){var c=g.Sa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},rfb=function(a){var b=g.Hm(a);
a=g.Km(a);return new g.vm(b.x,b.y,a.width,a.height)},sfb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Ls(a,b,function(){g.Ms(e);c.apply(a,arguments)},d)},R2=function(a){a=g.Va(a);
delete P2[a];g.Lg(P2)&&Q2&&Q2.stop()},ufb=function(){Q2||(Q2=new g.op(function(){tfb()},20));
var a=Q2;a.isActive()||a.start()},tfb=function(){var a=g.Za();
g.Bg(P2,function(b){vfb(b,a)});
g.Lg(P2)||ufb()},S2=function(a,b,c,d){g.Bp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.U=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.L=0;this.D=null},vfb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.L=1E3/(b-a.D);a.D=b;wfb(a,a.progress);a.progress==1?(a.j=0,R2(a),a.onFinish(),a.Ks()):a.isPlaying()&&a.RN()},wfb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.U[c]-a.B[c])*b+a.B[c]},xfb=function(a,b){g.Th.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.L;this.state=b.j},T2=function(a,b,c,d,e){S2.call(this,b,c,d,e);
this.element=a},yfb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
T2.call(this,a,b,c,d,e)},zfb=function(a){return Math.pow(a,3)},Afb=function(a){return 3*a*a-2*a*a*a},Bfb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},U2=function(a){return a.baseUrl||null},V2=function(a,b){return g.un(g.Jl(a,b),function(c){return!!c})},Cfb=function(a,b,c){function d(na){var X=na.hovercardButton;
if(!X)return null;X=X.subscribeButtonRenderer;if(!X)return null;var R=f(X.unsubscribedButtonText),Y=f(X.subscribedButtonText);if(X.subscribed){var v=f(X.subscriberCountWithUnsubscribeText);var U=f(X.subscriberCountText)}else v=f(X.subscriberCountText),U=f(X.subscriberCountWithSubscribeText);var $a=null;if(na.signinEndpoint){$a=O2(na,"signinEndpoint","webNavigationEndpointData","url");if(!$a){var vb,ob;$a=(ob=g.Q((vb=X.signInEndpoint)==null?void 0:vb.commandMetadata,g.G1))==null?void 0:ob.url}if(!$a)return null}return R&&
(Y||$a)?{subscribed:X.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:Y,unsubscribeCount:U,enabled:X.enabled,signinUrl:$a,classic:na.useClassicSubscribeButton}:null}
function e(na){if(na){var X=[],R=na.videoId;R&&X.push("v="+R);(R=na.playlistId)&&X.push("list="+R);(na=na.startTimeSeconds)&&X.push("t="+na);return"/watch?"+X.join("&")}}
function f(na){if(!na)return null;var X=na.simpleText;return X?X:na.runs?g.Jl(na.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,F=null,H=null,K=null,N=null;if(h==="VIDEO")g.Q(l,g.fy)?m=g.Q(l,g.fy).url:(N=g.Q(l,g.gR),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.fy)?m=g.Q(l,g.fy).url:(N=g.Q(l,g.gR),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=O2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=O2(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=O2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=O2(b,"title","accessibility","accessibilityData","label");var W=b.endpoint?b.endpoint.clickTrackingParams:
null,V="";if(b.metadata){var da=f(b.metadata);da&&(V=da)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),xY:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,kG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,X$:n,sessionData:W?{itct:W}:null,Ffa:q,AE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:V2(b.impressionUrls||[],U2),K$:V2(b.hovercardShowUrls||[],U2),clickUrls:V2(l.loggingUrls||[],U2),visualElement:g.Qw(b.trackingParams),productPrice:H,additionalFeesText:K,watchEndpoint:N||null}},Dfb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:V2(a.impressionUrls||[],U2),elements:V2(a.elements||[],function(d,e){return Cfb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Qw(a.trackingParams));return c},Efb=function(a){g.cY.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.U=[];this.Z=!0;this.L=0;a=a.V();this.W=g.JP(a)||g.LP(a);this.events=new g.ZF(this);g.P(this,this.events);this.events.T(this.player,g.yE("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.zE("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.lc);this.events.T(window,"focus",this.Dda);this.load();var b=g.jh("STYLE");(g.ah("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.oh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Ffb=function(a){return a.player.getVideoData().Nf?"current":a.W?"new":"current"},W2=function(a){return a.player.V().playerStyle==="creator-endscreen-editor"},Gfb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Dfb(f,Ffb(a))));X2(a,f)},
urlParams:{v:c},withCredentials:!0};a.W&&(c.urlParams.ptype="embedded");var d=b.Mw;d&&(c.postParams={ad_tracking:d});if(b=g.KMa(b))if(b=g.Nf(b),b=g.Jf(b))a.C=g.Or(b,c)},X2=function(a,b,c){c=c===void 0?!0:c;
a.player.Ze("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.U.length>0&&(a.U.forEach(function(l){l.dispose()}),a.U.length=0);
a.L=0;if((a.endscreen=b)&&b.elements){c&&Hfb(a);c=[];d=new g.wE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().B||(a.B=new g.S({J:"div",S:"ytp-ce-shadow"}),g.mS(a.player,a.B.element,4),a.D=new g.yy(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Ifb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.mS(a.player,f.element,4);var h=new g.wE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Jfb(a,f,e)}else g.bx(new g.it("buildEndscreenElement null",
e))}a.player.df(c);a.lc()}},Hfb=function(a){var b=g.Sw(),c=g.Tw();
c&&b&&a.endscreen.visualElement&&g.nr(g.nx)(void 0,c,b,a.endscreen.visualElement)},Ifb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={J:"div",Ka:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.AE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-covering-image",Y:Y2(b)},{J:"div",S:"ytp-ce-covering-shadow-top"},{J:"a",S:"ytp-ce-covering-overlay",Y:{href:Z2(a,b.targetUrl),tabindex:"-1"},X:[{J:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Fp(b.title||"")},ya:b.title},{J:"div",S:b.kG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={J:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.AE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-covering-image",Y:Y2(b)},{J:"div",S:"ytp-ce-covering-shadow-top"},{J:"a",S:"ytp-ce-covering-overlay",Y:{href:Z2(a,b.targetUrl),tabindex:"-1"},X:[{J:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Fp(b.title||"")},ya:b.title},{J:"div",S:"ytp-ce-playlist-count",
X:[{J:"div",S:"ytp-ce-playlist-icon"},{J:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={J:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.AE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-expanding-overlay",X:[{J:"div",S:"ytp-ce-expanding-overlay-hider"},{J:"div",S:"ytp-ce-expanding-overlay-background"},{J:"div",S:"ytp-ce-expanding-overlay-content",
X:[{J:"div",S:"ytp-ce-expanding-overlay-body",X:[{J:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{J:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Fp(b.title||"")},ya:b.title},b.subscribeButton?{J:"div",S:"ytp-ce-subscribe-container",X:[{J:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{J:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{J:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{J:"div",S:"ytp-ce-expanding-image",Y:Y2(b)}]};c=new g.S(c);var d=g.ch(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.wp(d,"ytp-ce-subscribe-button");if(a.player.V().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.HY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.U.push(e)}break;case "WEBSITE":a={J:"div",Ka:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.AE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-expanding-overlay",X:[{J:"div",S:"ytp-ce-expanding-overlay-hider"},{J:"div",S:"ytp-ce-expanding-overlay-background"},{J:"div",S:"ytp-ce-expanding-overlay-content",X:[{J:"div",S:"ytp-ce-expanding-overlay-body",X:[{J:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{J:"div",S:"ytp-ce-website-title",Y:{dir:g.Fp(b.title||"")},ya:b.title},{J:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{J:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{J:"div",S:"ytp-ce-expanding-image",Y:Y2(b)},{J:"div",S:"ytp-ce-expanding-icon",Y:Kfb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={J:"div",S:"ytp-ce-merchandise-price-container",
X:[{J:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.X.push({J:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={J:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.AE||"","aria-hidden":"true"},X:[{J:"div",S:"ytp-ce-element-shadow"},{J:"div",S:"ytp-ce-expanding-overlay",X:[{J:"div",S:"ytp-ce-expanding-overlay-hider"},{J:"div",S:"ytp-ce-expanding-overlay-background"},{J:"div",S:"ytp-ce-expanding-overlay-content",
X:[{J:"div",S:"ytp-ce-expanding-overlay-body",X:[{J:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{J:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.Fp(b.title||"")},ya:b.title},c,{J:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{J:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{J:"div",S:"ytp-ce-expanding-image",Y:Y2(b)},{J:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{J:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.wp(c.element,"ytp-ce-placeholder");return c},Y2=function(a){if(a.xY)var b=a.xY.thumbnails;
return Kfb(b?b[b.length-1].url:null)},Kfb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Jfb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.L+=m;a.L>0?(g.wp(b.element,"ytp-ce-force-expand"),$2(a,c.id,!0)):(g.yp(b.element,"ytp-ce-force-expand"),g.yp(b.element,"ytp-ce-element-hover"),$2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Lfb(a,b,c)});
b.listen("mouseleave",function(){Mfb(a,b,c)});
a.player.V().B||b.listen("click",function(){g.wp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Nfb(a,c,m)});
b.listen("keypress",function(m){Nfb(a,c,m)});
b.listen("focus",function(){Lfb(a,b,c)});
b.listen("blur",function(){Mfb(a,b,c)});
b.listen("touchstart",function(){Lfb(a,b,c)});
var l=g.dh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.yp(b.element,"ytp-ce-element-hover");g.yp(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Z=m.keyCode===9&&!m.shiftKey});
d(g.dh("ytp-sb-subscribe",b.element));d(g.dh("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Nfb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.vp(d,"ytp-ce-element");){g.vp(d,"subscribe-label")&&Ofb(a,b);
if(g.vp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.vp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Mfb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Ffa==="new")Ofb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Nf(Z2(a,b.targetUrl)),c=g.Jf(c),g.mz(c,void 0,b.sessionData);else{var e=g.YP(a.player.V())||a.player.getVideoData().Nf,f=function(){var h=Z2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.tr(h);e&&n&&(n.v||n.list)?a.player.Jp(n.v,l,n.list,!1,void 0,m||void 0):g.lz(h,l)};
Ofb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Z2=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.fQ(a)+b}else return"";return b},Lfb=function(a,b,c){g.vp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.wp(b.element,"ytp-ce-element-hover"):a.player.V().B?(new g.op(function(){g.wp(b.element,"ytp-ce-element-hover")},200)).start():g.wp(b.element,"ytp-ce-element-hover"),a3(a,c.K$),$2(a,c.id,!0))},Mfb=function(a,b,c){g.yp(b.element,"ytp-ce-element-hover");
g.yp(b.element,"ytp-ce-force-expand");$2(a,c.id,!1)},$2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Ap(a.j[e].element,"ytp-ce-element-shadow-show",c)},a3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||W2(a))c&&c();else{b=Pfb(a,b);var e=0,f=!1,h=new g.op(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.jv(b[a],d)}},Ofb=function(a,b,c){a3(a,b.clickUrls,c);
(a=g.Tw())&&b.X$&&g.yx(a,b.visualElement)},Pfb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Qfb(b[d],c));return a},Qfb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Rfb=function(a){return typeof a==="string"?a:""},b3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Sfb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},c3=function(a){return a.value?a.value:null},d3=function(a){if(!a)return null;
var b=g.Nf(Rfb(a.value));b=g.Jf(b);if(!b)return null;var c=b3(a.target,Tfb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Sfb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},Ufb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Xfb=function(a){if(!a)return null;
var b=b3(a.type,Vfb),c=b3(a.trigger,Wfb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=d3(a?a:null);return b?new Ufb(b,c,a):null},Yfb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Zfb=function(a,b){return g.Tb(a.action,b)},$fb=function(a,b){this.context=a;
this.j=b},agb=function(a){return a.customMessage?e3("div","iv-card-message",a.customMessage):""},f3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{J:"div",S:"iv-card-image",Y:{style:a},X:c}},bgb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(e3("li","",c.value));return{J:"ul",S:"iv-card-meta-info",X:b}},e3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Fp(c);return{J:a,Y:b,ya:c}},cgb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.NE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.NE+");");c.dir=g.Fp(a.customMessage);var d=[{J:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({J:"span",S:"iv-card-link-icon"}));return{J:"div",Ka:b,Y:c,X:d}},g3=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Aj.click,5)}},dgb=function(a,b){this.merchant=a;
this.price=b},egb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},fgb=function(a,b){return b?b:egb(a)?"current":"new"},h3=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Ua=new Map;this.Ya=new Map;this.context.K.addEventListener(g.yE("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)});
this.context.K.addEventListener(g.zE("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)})},i3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.SN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},ggb=function(a){var b;
return((b=g.Q(a,g.fy))==null?0:b.url)?g.Q(a,g.fy).url:(a=g.Q(a,g.gR))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},j3=function(a,b,c){return{VZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
o3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},hgb=function(a,b,c){h3.call(this,b,c);
var d=this;this.K=a;this.eventId=null;this.Db=this.La=this.Ib=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.W=this.Ma=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.U=this.Jf=this.Fa=null;this.L=0;this.Da=new g.op(function(){},c.ea.xk?4E3:3E3);
g.P(this,this.Da);this.ib=new g.op(function(){});
g.P(this,this.ib);this.Ba=new $fb(c,function(e,f,h,l,m,n){i3(d,e,f,h,l,m,n)});
this.Z=new g.S({J:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{J:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{J:"span",S:"iv-drawer-header-text"},{J:"button",Ka:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{J:"div",S:"iv-drawer-content"}]});g.P(this,this.Z);this.D=this.Z.element;this.bb=new g.yy(this.Z,330);g.P(this,this.bb);this.Kb=g.dh("iv-drawer-header-text",this.D);this.B=g.dh("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Ib&&k3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ib=d.C)&&l3(d)});
this.Pa=new g.ZF(this);g.P(this,this.Pa);this.K.addEventListener("videodatachange",this.Cu.bind(this))},igb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){k3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){l3(a)});
var c=b.headerText;g.qh(a.Kb,c);a.W&&a.W.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.Qw(b.trackingParams);a.U=g.Qw(b.closeTrackingParams);a.Jf=g.Qw(b.iconTrackingParams)},jgb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.L,d=a.K.V().experiments.eb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"simple",teaserText:g.Mx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Aj:{},Zp:null,nk:e.trackingParams?g.Qw(e.trackingParams):null,Jf:f&&f.trackingParams?g.Qw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
NE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};m3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"simple",teaserText:g.Mx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:n3(a,c,b,f),sponsored:!1,Aj:j3(f,e,f.command),Zp:f.trackingParams?g.Qw(f.trackingParams):null,nk:e.trackingParams?g.Qw(e.trackingParams):null,Jf:l&&l.trackingParams?g.Qw(l.trackingParams):null,imageUrl:o3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Mx(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,NE:null,title:f.title?g.Mx(f.title):"",customMessage:f.callToAction?g.Mx(f.callToAction):"",url:g.Q(f.command,g.fy).url?d3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.fy).url}):null,onClickCommand:null};m3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"collaborator",teaserText:g.Mx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:n3(a,c,b,e),sponsored:!1,Aj:j3(e,f,e.endpoint),Zp:e.trackingParams?g.Qw(e.trackingParams):null,nk:f.trackingParams?g.Qw(f.trackingParams):null,Jf:l&&l.trackingParams?g.Qw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.vR).browseId,customMessage:e.customText?g.Mx(e.customText):null,profileImageUrl:o3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Mx(e.channelName):"",metaInfo:[e.subscriberCountText?g.Mx(e.subscriberCountText):""],url:d3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.vR).canonicalBaseUrl?g.Q(e.endpoint,g.vR).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.vR).browseId}),onClickCommand:null};m3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"playlist",teaserText:g.Mx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:n3(a,c,b,e),sponsored:!1,Aj:j3(e,f,e.action),Zp:e.trackingParams?g.Qw(e.trackingParams):null,nk:f.trackingParams?g.Qw(f.trackingParams):null,Jf:l&&l.trackingParams?g.Qw(l.trackingParams):null,rI:o3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Mx(e.customMessage):null,playlistVideoCount:g.Mx(e.playlistVideoCount),title:e.playlistTitle?g.Mx(e.playlistTitle):"",metaInfo:[e.channelName?g.Mx(e.channelName):
"",e.videoCountText?g.Mx(e.videoCountText):""],url:d3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ggb(e.action)}),onClickCommand:null};m3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.L,type:"video",teaserText:g.Mx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:n3(a,c,b,e),sponsored:!1,Aj:j3(e,f,e.action),Zp:e.trackingParams?g.Qw(e.trackingParams):null,nk:f.trackingParams?g.Qw(f.trackingParams):null,Jf:l&&l.trackingParams?g.Qw(l.trackingParams):null,rI:o3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Mx(e.lengthString):null,customMessage:e.customMessage?g.Mx(e.customMessage):null,title:e.videoTitle?g.Mx(e.videoTitle):"",metaInfo:[e.channelName?g.Mx(e.channelName):
"",e.viewCountText?g.Mx(e.viewCountText):""],isLiveNow:!!e.badge,url:d3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ggb(e.action)}),onClickCommand:null};m3(a,b)}}}}}a.L++},o3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},n3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},lgb=function(a,b){if(b=kgb(a,b))b===a.j&&(a.j=null),a.K.removeCueRange(b.Ef.id),g.oh(b.fP),g.Xb(a.cards,b),a.yJ(),p3(a)},k3=function(a,b,c){if(!a.C){a.bb.show();
a.Va=new g.op(function(){g.wp(a.context.K.getRootNode(),g.M_.IV_DRAWER_OPEN)},0);
a.Va.start();a.Pa.T(a.B,"mousewheel",function(h){a.Da.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Tw();d&&a.Fa&&a.U&&g.wx(d,[a.Fa,a.U]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.W_||(f.W_=!0,mgb(a.context.logger,f.Ef.Aj.VZ,b)),d&&g.wx(d,[f.Ef.Zp]);N2(a.K);c&&(a.G=new g.op(function(){a.Ma=a.W;a.tb.focus()},330),a.G.start())}},l3=function(a){a.C&&(a.bb.hide(),g.Ss(a.Pa),g.yp(a.context.K.getRootNode(),g.M_.IV_DRAWER_OPEN),a.C=!1,N2(a.K),a.G&&a.G.stop(),a.G=new g.op(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},ngb=function(a){g.xp(a.Jb(),
[g.M_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.mS(a.K,a.D,5);a.kJ();a.W=g.dh("ytp-cards-button",a.K.getRootNode());a.tb=g.dh("iv-drawer-close-button",a.D);a.isInitialized=!0},ogb=function(a){a.qa.push(g.Cv("iv-teaser-shown",a.j5,a));
a.qa.push(g.Cv("iv-teaser-hidden",a.vaa,a));a.qa.push(g.Cv("iv-teaser-clicked",a.i5,a));a.Db=!0},pgb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.adb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},qgb=function(a,b){a.ra=b;
var c=a.K.getVideoData();if(!c)return!1;c=g.BQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.O4a))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},m3=function(a,b){if(!pgb(a,b)||qgb(a,b)){var c=rgb(a,b);
if(c){var d={Ef:b,fP:c.element,W_:!1};if(b.onClickCommand)a.K.N("web_infocards_teaser_show_logging_fix")&&(a.Db||ogb(a),lgb(a,b.id),c=a.findLastIndex(d),g.cc(a.cards,c,0,d));else{a.isInitialized||ngb(a);lgb(a,b.id);var e=a.findLastIndex(d);g.cc(a.cards,e,0,d);c.Ia(a.B,e);a.yJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,p3(a),sgb(a,d),k3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.K.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&tgb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){tgb(a,d)}),p3(a))}}},rgb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{J:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=cgb(b);c={J:"div",Ka:["iv-card"],X:[{J:"a",S:"iv-click-target",Y:{href:b.url?c3(b.url)||"":""},X:[f3(b.imageUrl,c),{J:"div",S:"iv-card-content",X:[e3("h2",void 0,b.title),d]}]}]};c=new g.S(c);g3(a,g.bh("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={J:"div",Ka:["iv-card","iv-card-channel"],X:[{J:"a",Ka:["iv-click-target"],Y:{href:c3(b.url)||"","data-ytid":b.channelId},X:[f3(b.profileImageUrl),
{J:"div",S:"iv-card-content",X:[agb(b),{J:"h2",S:"iv-card-primary-link",ya:b.title},bgb(b)]}]}]};c=new g.S(c);g3(a,g.bh("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={J:"div",Ka:["iv-card","iv-card-playlist"],X:[{J:"a",S:"iv-click-target",Y:{href:c3(b.url)||""},X:[f3(b.rI,{J:"div",S:"iv-card-image-overlay",X:[{J:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{J:"div",S:"iv-card-content",X:[agb(b),e3("h2","iv-card-primary-link",b.title),bgb(b)]}]}]};
c=new g.S(c);g3(a,g.bh("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=b.offers.length!=0;c=["iv-card"];d="";var f=cgb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({J:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({J:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={J:"div",X:e});e=b.url?c3(b.url)||"":"";c={J:"div",Ka:c,Y:{tabindex:"0"},X:[{J:"a",Ka:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{J:"div",S:"iv-card-content",X:[b.sponsored?{J:"div",S:"iv-card-sponsored",X:["Sponsored",{J:"div",S:"iv-ad-info-container",X:[{J:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{J:"div",S:"iv-ad-info-icon-container",X:[{J:"div",S:"iv-ad-info-icon"},{J:"div",S:"iv-ad-info-callout"}]}]}]}:"",{J:"a",S:"iv-click-target",Y:{href:e},X:[e3("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.jh("span");g.qh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Dd(d,"adInfo");g3(a,g.bh("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{J:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{J:"span",Ka:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={J:"div",Ka:["iv-card","iv-card-video"],X:[{J:"a",S:"iv-click-target",Y:{href:((c=b.url)==null?void 0:c3(c))||""},X:[f3(b.rI,d),{J:"div",S:"iv-card-content",X:[agb(b),e3("h2","iv-card-primary-link",b.title),bgb(b),f]}]}]};c=new g.S(e);g3(a,g.bh("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},ugb=function(a){if(a.j)return a.j.Ef.type==="productListing";
if(a.K.N("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Kl(a.cards,function(c){return c.Ef.type==="productListing"})}return g.Kl(a.cards,function(c){return c.Ef.type==="productListing"})},p3=function(a){g.Ap(a.K.getRootNode(),"ytp-cards-shopping-active",ugb(a))},tgb=function(a,b){if(!g.vp(a.K.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Tw(),d=a.j?a.j.Ef.Jf:a.Jf;
c&&d&&g.xx(c,[d]);a.j=b;p3(a)}(c=a.isInitialized&&a.Jb().style.display=="none")||(c=a.context.K.getPlayerState(),d=c===0&&a.context.K.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Ef.teaserDurationMs&&a.K.DC(!0,{teaserText:b.Ef.teaserText,durationMs:b.Ef.teaserDurationMs,onClickCommand:b.Ef.onClickCommand});a.ib.isActive()||((!a.C||!a.Da.isActive()&&a.La)&&sgb(a,b),a.ib.start(910+b.Ef.teaserDurationMs))}},sgb=function(a,b){a.Z.Eb?(b=new S2([0,
a.B.scrollTop],[0,b.fP.offsetTop],600,Afb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Ix(a.Z,!0),a.B.scrollTop=b.fP.offsetTop,g.Ix(a.Z,!1))},q3=function(a){return a.j&&a.j.Ef?a.j.Ef:a.cards[0]&&a.cards[0].Ef?a.cards[0].Ef:null},kgb=function(a,b){return g.Tb(a.cards,function(c){return c.Ef.id===b})},r3=function(a,b,c){h3.call(this,a,b);
this.annotation=c;this.isActive=!1},vgb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},s3=function(a,b,c){r3.call(this,a,b,c);
this.B=null;this.U=!1;this.C=null;this.D=!1;this.j=this.L=this.G=null},wgb=function(a,b){var c=c===void 0?0:c;
var d=rfb(b).width;g.Fm(b,d);c=new yfb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,zfb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Lm(b,!0)});
c.play()},zgb=function(a,b){if(b.channel_name){var c=a.createElement({J:"div",
Ka:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({J:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.HY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.K,!1),a.j.Ia(d));var f=a.createElement({J:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({J:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Lm(h,!1);var l=a.createElement({J:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.ym(l,"right",b.image_width+"px");g.lh(a.Jb(),l);a.C=new g.op(function(){xgb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Jb(),"mouseover",function(){ygb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Jb(),"mouseout",function(){a.C.start()})}},ygb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Km(b);a.j||(b.style.width=g.Em(f.width,!0),c.style.width=g.Em(f.width,!0));g.ym(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ym(d,"right","1px");a.D=!0;g.Lm(b,!0);a.G=new g.op(function(){g.wp(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},xgb=function(a,b,c){g.yp(a.Jb(),"iv-branding-active");
a.L=new g.op(function(){g.Lm(b,!1);a.j||(c.style.width=g.Em(0,!0))},250);
a.L.start();a.D=!1},Agb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.ea=c;this.videoData=d;this.logger=e;this.K=f;this.B=h},Bgb=function(a,b,c){r3.call(this,a,b,c);
var d=this;this.W=this.isCollapsed=this.Z=!1;this.L=5E3;this.B=this.C=this.j=this.D=null;this.U=this.createElement({J:"div",Ka:["iv-promo-contents"]});this.G=new g.op(function(){d.j.setAttribute("aria-hidden","true");g.Lm(d.C,!1);g.Lm(d.B,!0)},700,this);
g.P(this,this.G)},Egb=function(a,b,c){c.stopPropagation();
Cgb(a);Dgb(a,b);a.j.focus()},Fgb=function(a){a.isCollapsed||a.W||a.D||(g.wp(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Cgb=function(a){a.G.stop();
a.isCollapsed&&(g.zp(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Lm(a.B,!1),g.Lm(a.C,!0))},Dgb=function(a,b){a.D||(a.D=g.Hi(function(){Ggb(this);
Fgb(this)},b,a))},Ggb=function(a){a.D&&(g.Na.clearTimeout(a.D),a.D=null)},Hgb=function(a){this.K=a},mgb=function(a,b,c){b&&(c?t3(a,b.map(function(d){return g.So(d,c)})):t3(a,b))},t3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.jv(m,f);d&&(e++,d!==0&&a.K.sendVideoStatsEngageEvent(d,f))},Igb=function(a){g.cY.call(this,a);
var b=this;this.qa=this.W=!1;this.loadNumber=0;this.L={};this.logger=new Hgb(this.player);this.D=new g.ZF(this);this.G=this.U=null;this.events=new g.ZF(this);this.ph=this.Z=this.j=null;this.ra=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.k5,this);this.subscribe("resize",this.iM,this);this.player.V().La.subscribe("vast_info_card_add",this.o1,this);g.P(this,this.events);this.Ba=this.createElement({J:"div",S:"video-custom-annotations"});this.B=new g.S({J:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.mS(this.player,this.B.element,4);this.B.hide();this.C=new g.S({J:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({J:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.Mv()&&this.load();var c=this.createElement({J:"style"});(g.ah("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.oh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Jgb=function(a){a=a.createElement({J:"div",
Ka:["annotation","annotation-type-custom"]});g.Lm(a,!1);return a},Kgb=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.Ix(a.B,b);g.Ix(a.C,b)},Lgb=function(a,b,c){a.W=!0;
a.G=g.Or(b,c)},Mgb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ta(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Mgb(a,e))}return c},Qgb=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.V().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.Dr(h)&&h.responseXML?h.responseXML:null)&&Ngb(a,h)}};
g.qt()&&(d.onFinish=Ogb(a,d.onFinish));d.postParams={ic_only:"1"};Pgb(d,c);a.W=!0;g.Or(b.Ua,d)}}},Pgb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.DJ&&(a.postParams.ic_coll=b.DJ);b.gP&&(a.postParams.ic_xml=b.gP);b.zN&&(a.postParams.ic_track=b.zN)},Rgb=function(a){var b=new g.S({J:"div"});
g.Lm(b.element,!1);var c=new hgb(a.player,b.element,u3(a));g.P(c,b);b.Ia(a.B.element);c.aI();return c},Tgb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,Sgb(a,b),b.headerText&&a.ph&&(c=g.Mx(b.headerText),a.ph.setAttribute("title",c))},u3=function(a){if(!a.Z){var b=new Bfb(a);
g.P(a,b);var c=new g.Ik(a);g.P(a,c);a.Z=new Agb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Uj)}return a.Z},Ngb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Tw();if(e){var f=g.Sw();f&&g.nr(g.mx)(void 0,e,f,[g.Qw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Mgb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=b3(f.type,Ugb),p=b3(f.style,Vgb),q=Rfb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=Xfb;if(t==null)var u=null;else if(g.Sa(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new Yfb(m,n,p,u,r):null}else e=null}catch(da){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Jgb(f),K=null;switch(l.type){case "branding":if(f.player.V().Fd)break;f.B.element.appendChild(H);K=new s3(H,u3(f),l);break;case "promotion":g.mS(f.player,H,4),K=new Bgb(H,u3(f),l)}K&&K.aI();if(f=K)g.P(a,f),a.L[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=Rgb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={VZ:f.impression,click:f.click,close:f.close,o3:f.teaser_impression,uN:f.teaser_click},l=e.tracking_params||{},K=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Aj:f,Zp:l.card?g.Qw(l.card):null,nk:l.teaser?g.Qw(l.teaser):null,Jf:l.icon?g.Qw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};m3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Aj:f,
Zp:l.card?g.Qw(l.card):null,nk:l.teaser?g.Qw(l.teaser):null,Jf:l.icon?g.Qw(l.icon):null,rI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};m3(H,c);break;case "productListing":e.signin_url&&(K=d3({target:"current",value:e.signin_url}));N=[];for(var W=e.offers||[],V=0;V<W.length;V++)N.push(new dgb(g.gg(W[V].merchant),
g.gg(W[V].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Aj:f,Zp:l.card?g.Qw(l.card):null,nk:l.teaser?g.Qw(l.teaser):null,Jf:l.icon?g.Qw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,NE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Mqa:K,Lqa:e.signin_title?e.signin_title:void 0,Kqa:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};m3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Aj:f,Zp:l.card?g.Qw(l.card):
null,nk:l.teaser?g.Qw(l.teaser):null,Jf:l.icon?g.Qw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,NE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};m3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,Aj:f,Zp:l.card?g.Qw(l.card):null,nk:l.teaser?g.Qw(l.teaser):null,Jf:l.icon?g.Qw(l.icon):null,rI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:d3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},m3(H,c)}}else igb(a.j,e);c=!0}}c&&
(N2(a.player),a.iM())},Sgb=function(a,b){var c=!1;
a.j||(a.j=Rgb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(jgb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.CR(f)||(c=a.j,d=b.headerText?g.Mx(b.headerText):"",g.qh(c.Kb,d),c.W&&c.W.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.Qw(b.trackingParams):null,c.U=b.closeButton.infoCardIconRenderer.trackingParams?g.Qw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Jf=b.icon.infoCardIconRenderer.trackingParams?g.Qw(b.icon.infoCardIconRenderer.trackingParams):null,a.iM());N2(a.player)}},Wgb=function(a,b,c,d,e){if(!a.player.V().Fd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.vR)&&g.Q(b.navigationEndpoint,g.vR).browseId&&f.push(new Ufb("openUrl","click",new Sfb("/channel/"+g.Q(b.navigationEndpoint,g.vR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.wR)){d.channel_id=g.Q(b.subscribeButton,g.wR).channelId;var l;b=g.Q(b.subscribeButton,g.wR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Mx(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Mx(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Mx(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Mx(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.G1))==null?void 0:m.url)||"";l={subscribeText:g.Mx(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Mx(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Yfb(c,"branding","branding",f,d);l=Jgb(a);a.B.element.appendChild(l);f=new s3(l,u3(a),f);f.aI();g.P(f,f);a.L[c]=f}},Ogb=function(a,b){return function(){var c=g.Ea.apply(0,arguments);
a.Ja()||a.ra.push(g.hp.bj(function(){b.apply(null,g.x(c))}))}},Xgb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.fS.prototype.DC=g.ca(35,function(a,b){var c=g.pY(this.Bb());c&&c.DC(a,b)});
var P2={},Q2=null;g.bb(S2,g.Bp);g.k=S2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;R2(this);this.startTime=a=g.Za();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.YL();this.Co("play");this.isPaused()&&this.Co("resume");this.j=1;var b=g.Va(this);b in P2||(P2[b]=this);ufb();vfb(this,a);return!0};
g.k.stop=function(a){R2(this);this.j=0;a&&(this.progress=1);wfb(this,this.progress);this.onStop();this.Ks()};
g.k.pause=function(){this.isPlaying()&&(R2(this),this.j=-1,this.Co("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.Co("destroy");S2.Xf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.RN=function(){this.Co("animate")};
g.k.Co=function(a){this.dispatchEvent(new xfb(a,this))};
g.bb(xfb,g.Th);g.bb(T2,S2);T2.prototype.C=function(){};
T2.prototype.RN=function(){this.C();T2.Xf.RN.call(this)};
T2.prototype.Ks=function(){this.C();T2.Xf.Ks.call(this)};
T2.prototype.YL=function(){this.C();T2.Xf.YL.call(this)};
g.bb(yfb,T2);yfb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(Bfb,g.O);g.k=Bfb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Xa)(c,d||this.B);a=g.Ls(a,b,c);this.j.push(a);return a};
g.k.AG=function(a,b,c,d){c=(0,g.Xa)(c,d||this.B);a=sfb(a,b,c);this.j.push(a);return a};
g.k.Oc=function(a){g.Ms(a);g.Xb(this.j,a)};
g.k.removeAll=function(){g.Ms(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.O.prototype.xa.call(this)};g.z(Efb,g.cY);g.k=Efb.prototype;g.k.load=function(){g.cY.prototype.load.call(this);if(!W2(this)){var a=g.LMa(this.player.getVideoData());a?(a=Dfb(a,Ffb(this)),X2(this,a,!1)):Gfb(this)}};
g.k.unload=function(){X2(this,null);this.C&&(this.C.abort(),this.C=null);g.cY.prototype.unload.call(this)};
g.k.oi=function(a,b){return W2(this)?a==="loadCustomEndscreenRenderer"?(a=Dfb(b,"new"),X2(this,a),!0):null:null};
g.k.getOptions=function(){return W2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.lc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Ygb.length;f++){var h=Math.abs(b.width-Ygb[f]);if(e===-1||d>=h)e=f,d=h}d=Zgb[e];this.B&&g.ym(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Jm(e.element,m,f);g.Fm(e.element,n,p);g.zp(e.element,$gb);m>256||f>256?g.wp(e.element,"ytp-ce-large-round"):m>96||f>96?g.wp(e.element,"ytp-ce-medium-round"):g.wp(e.element,"ytp-ce-small-round");g.zp(e.element,ahb);m=h.left+h.width/2;h=h.top+l/2;g.wp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zp(e.element,Zgb);g.wp(e.element,d);(e=g.ch(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ym(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")a3(this,this.endscreen.impressionUrls),(a=g.Tw())&&this.endscreen.visualElement&&g.vx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.wp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.wp(b,"ytp-ce-shown");a3(this,c.impressionUrls);(b=g.Tw())&&g.vx(b,c.visualElement);this.player.V().U&&this.player.gb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.yp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.yp(b,"ytp-ce-shown");this.player.V().U&&this.player.gb("endscreenelementhidden",a)}};
g.k.Dda=function(a){var b=this;a.target===window&&(new g.op(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.zp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Ygb=[346,426,470,506,570,640,853,1280,1920],Zgb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ahb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],$gb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Tfb={cia:"current",Gka:"new"};var Vfb={CLOSE:"close",Mka:"openUrl",SUBSCRIBE:"subscribe"},Wfb={Lha:"click",CLOSE:"close",eja:"hidden",Dla:"rollOut",Ela:"rollOver",Ola:"shown"};Yfb.prototype.le=function(){var a=Zfb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var Vgb={Wga:"anchored",J4:"branding",CHANNEL:"channel",bia:"cta",hja:"highlightText",Uja:"label",PLAYLIST:"playlist",POPUP:"popup",Wla:"speech",SUBSCRIBE:"subscribe",hma:"title",VIDEO:"video",Rma:"website"},Ugb={J4:"branding",zha:"card",qia:"drawer",gja:"highlight",lka:"marker",kla:"promotion",TEXT:"text",tna:"widget"};g.z(h3,g.O);g.k=h3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.wE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ua.set(a,d);e&&this.Ya.set(a,e);this.context.K.df([a],1)};
g.k.aI=function(){this.context.B.subscribe("resize",this.yJ,this)};
g.k.Jb=function(){return this.element};
g.k.SN=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.oh(this.Jb())};
g.k.yJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=c3(a);if(f){var h=fgb(f,a.target),l=function(){a.j&&e.context.K.pauseVideo();var m=e.context.videoData.Nf||!1,n=g.tr(f||"");m&&n&&(n.v||n.list)?e.context.K.Jp(n.v,b,n.list,!1):g.mz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);t3(this.context.logger,c,l,d);egb(f)||(c=g.Tw(),d=b.itct,c&&d&&g.yx(c,g.Qw(d)))}};
g.k.xa=function(){this.Ua.clear();this.Ya.clear();g.O.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.z(hgb,h3);g.k=hgb.prototype;g.k.Cu=function(){this.ra&&m3(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.K.getRootNode())?(a=g.Km(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.yJ=function(){var a=this.isAvailable();g.Lm(this.Jb(),a);g.Ap(this.context.K.getRootNode(),g.M_.IV_DRAWER_ENABLED,a);N2(this.K)};
g.k.destroy=function(){this.K.DC(!1);try{this.K.getRootNode().removeChild(this.D)}catch(a){}g.Dv(this.qa);g.Ss(this.Pa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();h3.prototype.destroy.call(this)};
g.k.kJ=function(){var a=this;this.context.j.listen(g.dh("iv-drawer-close-button",this.D),"click",this.n8,this);this.context.j.listen(this.B,"touchend",function(){a.Da.start()});
this.context.j.listen(this.B,"scroll",this.L8,this);this.context.B.subscribe("onHideControls",function(){a.La=!0});
this.context.B.subscribe("onShowControls",function(){a.La=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.La=g.vp(a.K.getRootNode(),"ytp-autohide")});
this.qa.push(g.Cv("iv-button-shown",this.uaa,this));this.qa.push(g.Cv("iv-button-hidden",this.taa,this));ogb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Ub(this.cards,function(c){return a.Ef.startMs>c.Ef.startMs||a.Ef.startMs===c.Ef.startMs&&a.Ef.timestamp>=c.Ef.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.n8=function(){if(this.C){t3(this.context.logger,q3(this).Aj.close);var a=g.Tw();a&&this.U&&g.yx(a,this.U);l3(this)}};
g.k.L8=function(){g.Ap(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.uaa=function(){var a=g.Tw(),b=q3(this);b=b?b.Jf:this.Jf;a&&b&&g.wx(a,[b])};
g.k.taa=function(){var a=g.Tw(),b=q3(this);b=b?b.Jf:this.Jf;a&&b&&g.xx(a,[b])};
g.k.j5=function(){var a=q3(this);t3(this.context.logger,a.Aj.o3);var b=g.Tw();if(b&&a)if(this.K.N("web_infocards_teaser_show_logging_fix")){var c=[];a.nk&&c.push(a.nk);a.Jf&&c.push(a.Jf);c.length>0&&g.wx(b,c)}else g.wx(b,[a.nk,a.Jf])};
g.k.vaa=function(){var a=g.Tw(),b=q3(this);a&&b&&g.xx(a,[b.nk])};
g.k.i5=function(a){var b=q3(this),c=g.Tw();this.j?a?(a=this.context.logger,t3(a,b.Aj.uN),a.K.sendVideoStatsEngageEvent(4,void 0),c&&b.nk&&g.yx(c,b.nk)):(a=this.context.logger,t3(a,b.Aj.uN),a.K.sendVideoStatsEngageEvent(4,void 0),c&&b.Jf&&g.yx(c,b.Jf)):(a=this.context.logger,t3(a,b.Aj.uN),a.K.sendVideoStatsEngageEvent(4,void 0),c&&this.Jf&&g.yx(c,this.Jf))};g.z(r3,h3);r3.prototype.aI=function(){h3.prototype.aI.call(this);vgb(this)};
r3.prototype.show=function(){h3.prototype.show.call(this);var a=g.Tw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.wx(a,[g.Qw(b.itct)])};
r3.prototype.hide=function(){h3.prototype.hide.call(this);var a=g.Tw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.xx(a,[g.Qw(b.itct)])};g.z(s3,r3);
s3.prototype.fz=function(){g.wp(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({J:"img",Ka:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Lm(this.B,!1);var b=this.createElement({J:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.le();c&&i3(this,b,c,this.annotation.id,a.session_data);this.context.K.N("disable_branding_context")||zgb(this,
a)};
s3.prototype.show=function(){if(!this.isActive&&(r3.prototype.show.call(this),this.U||(this.fz(),this.U=!0),g.Lm(this.Jb(),!0),this.isActive=!0,this.B)){try{wgb(this,this.B)}catch(a){}g.wp(this.context.K.getRootNode(),"ytp-branding-shown");this.context.K.getRootNode().style.setProperty("--branding-image-width",this.B.getAttribute("width")+"px")}};
s3.prototype.hide=function(){this.isActive&&(r3.prototype.hide.call(this),g.Lm(this.Jb(),!1),this.isActive=!1,g.yp(this.context.K.getRootNode(),"ytp-branding-shown"))};
s3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);r3.prototype.destroy.call(this)};g.z(Bgb,r3);g.k=Bgb.prototype;
g.k.fz=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.L=b.collapsedelay_ms||this.L;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promotion");this.Jb().tabIndex=0;var e=this.annotation.le(),f=b.image_url;if(f){var h=this.createElement({J:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({J:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({J:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({J:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&i3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({J:"a",S:"iv-promo-txt"}),g.Pf(f,c3(e)),this.j=f):this.j=this.createElement({J:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({J:"p",X:[{J:"strong",ya:b.text_line_1}]});var m=this.createElement({J:"p",X:[{J:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({J:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({J:"button",Ka:["iv-button","iv-promo-button"],X:[{J:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({J:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&i3(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.wp(this.j,"iv-click-target");e&&i3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({J:"p",X:[{J:"span",ya:b.text_line_1}]}),m=this.createElement({J:"p",X:[{J:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({J:"span",Ka:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.wp(this.j,"iv-click-target"),e&&i3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.U.appendChild(this.j);p&&this.U.appendChild(p);c=this.createElement({J:"div",S:"iv-promo-actions"});this.B=this.createElement({J:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){Egb(a,5E3,q)});
c.appendChild(this.B);g.Lm(this.B,!1);this.context.j.listen(this.Jb(),"mouseover",this.o$,this);this.context.j.listen(this.Jb(),"mouseout",this.n$,this);this.context.j.listen(this.Jb(),"touchend",function(q){Egb(a,5E3,q)});
this.C=this.createElement({J:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.j$:this.i$,this);c.appendChild(this.C);g.xp(this.Jb(),d);h&&(g.lh(this.Jb(),h),n&&h.appendChild(n));g.lh(this.Jb(),this.U);g.lh(this.Jb(),c)};
g.k.show=function(){this.isActive||(r3.prototype.show.call(this),this.Z||(this.fz(),this.Z=!0),g.Lm(this.Jb(),!0),g.Hi(function(){g.yp(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,Ggb(this),Cgb(this),Dgb(this,this.L))};
g.k.hide=function(){this.isActive&&(g.wp(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.SN=function(a,b,c,d,e,f){return this.isCollapsed?!1:r3.prototype.SN.call(this,a,b,c,d,e,f)};
g.k.o$=function(a){this.W=!0;Egb(this,500,a)};
g.k.n$=function(){this.W=!1;Fgb(this)};
g.k.i$=function(a){a.stopPropagation();this.hide()};
g.k.j$=function(a){a.stopPropagation();Ggb(this);this.isCollapsed=!0;g.wp(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();r3.prototype.destroy.call(this)};g.z(Igb,g.cY);g.k=Igb.prototype;g.k.oi=function(a,b){if(!Xgb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.j1(b))&&Ngb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(lgb(this.j,b),N2(this.player)),!0}return null};
g.k.getOptions=function(){return Xgb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Mv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.MR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.x4||a.La.get(b.videoId)||g.DR(b)||g.MMa(b)?!0:!1};
g.k.iM=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.Jm(this.C.element,a.width,a.height);g.Fm(this.C.element,a.left,a.top)}if(this.j){var b=this.player.fn();a=this.j;b=b.width;g.Ap(a.D,"iv-drawer-small",b<=426);g.Ap(a.D,"iv-drawer-big",b>=1280)}};
g.k.k5=function(a){Kgb(this,a.state);g.T(a.state,2)&&(this.Nl()&&this.Wp()&&this.player.getPresentingPlayerType()!==2&&this.EC(!1),this.DC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Dr(h)&&h.responseXML?h.responseXML:null)&&(Ngb(b,h),g.wp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.cY.prototype.load.call(this);Kgb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.qt()&&(a=Ogb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().La.get(d);f&&Pgb(e,f);f=f&&(f.gP||f.DJ);if(!c.Bw||f)c.Ua?Lgb(this,c.Ua,e):(this.U=function(){if(!b.W)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.CR(h))&&!b.qa&&Tgb(b,h)},this.player.addEventListener("videodatachange",this.U));
g.mS(this.player,this.C.element,4);this.iM();(f=g.DR(c))&&Sgb(this,f);(f=g.MMa(c))&&f.featuredChannel&&Wgb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.ph=g.dh("ytp-cards-button",this.player.getRootNode());g.CR(c)&&Tgb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&Lgb(this,b.Ua,a)};
g.k.unload=function(){this.player.Ze("annotations_module");for(var a=g.w(Object.keys(this.L)),b=a.next();!b.done;b=a.next())this.L[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,N2(this.player));this.W=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.L={};this.B.hide();g.cY.prototype.unload.call(this);this.C.detach();this.U&&(this.player.removeEventListener("videodatachange",this.U),this.U=null)};
g.k.o1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Qgb(this):this.load())};
g.k.Nl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Wp=function(){return!!this.j&&this.j.C};
g.k.EC=function(a,b,c){b=b===void 0?!1:b;this.Nl();this.j&&(a?c?k3(this.j,c,b):k3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):l3(this.j))};
g.k.DC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.V().La.unsubscribe("vast_info_card_add",this.o1,this);g.yp(this.player.getRootNode(),g.M_.IV_DRAWER_OPEN);for(var a=this.ra,b=g.hp,c=0,d=a.length;c<d;c++)b.Ck(a[c]);this.ra.length=0;g.cY.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.bY("annotations_module",Igb);g.bY("creatorendscreen",Efb);})(_yt_player);
