(function(g){var window=this;'use strict';var dhb=function(a,b,c){g.I(function(d){a.B=g.Or(b,c);g.va(d)})},v3=function(a){a.isActive()||a.start()},ehb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},fhb=function(a){return g.YP(a)||a.N("web_enable_caption_language_preference_stickiness")},ghb=function(a,b){var c=new g.oQ;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},hhb=function(a,b){var c,d,e;
return g.I(function(f){if(f.j==1)return c=a+"|"+b,g.G(f,g.pu(),2);if(f.j!=3){d=f.B;if(!d)throw g.Mt("gct");return g.G(f,g.GQ(d),3)}e=f.B;return f.return(e.get("captions",c))})},ihb=function(a,b,c){hhb(a,b).then(function(d){d&&c(d.trackData,new g.oQ(d.metadata))})},lhb=function(a){if(!jhb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(khb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},mhb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.Odb?g.Odb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={sG:c.sG};c.sG=d;var e=function(f){return function(){return String(a[f.sG])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.sG+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.sG,"gi"),e)}return b},nhb=function(){return g.Xs("yt-player-caption-display-settings")},w3=function(){this.segments=[]},ohb=function(a,b){var c=g.ec(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Wb(a.segments,c),g.Wb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.cc(a.segments,c,0,b),g.cc(a.segments,c+1,0,b)))},phb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.qa=c;this.W=d;this.G=e;this.Z=f;this.D=new w3;this.L=-1;this.C=this.B=this.j=null;this.ra=0;this.U=new g.op(this.M_,1E3,this);this.events=new g.ZF(this);g.P(this,this.U);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.VB);this.VB();this.M_()},qhb=function(a){return a.j&&a.j.Wf?a.j.Wf+a.player.Nc()<a.player.getCurrentTime():!1},rhb=function(a,b){if(a.policy.Hm&&a.player.wu()){var c=g.SN(b,a.policy,{});
c.set("pot",a.player.wu());c=c.le()}else c=g.SN(b,a.policy,{}).le();var d={format:"RAW",withCredentials:!0};if(a.policy.La){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.AB(e,g.cM):d.postBody=(0,g.TT)([120,0])}a.G&&(d.responseType="arraybuffer");var f=++a.ra,h=(0,g.St)();a.C=g.Sr(c,d,3,100).then(function(l){if(a.policy.LI&&f%100===1){var m=(0,g.St)();a.player.oa("caprsp",{rn:f,ms:m-h,kb:(l.xhr.responseText.length/1024).toFixed()})}a:{l=l.xhr;a.Ja();if(a.B){var n=!(a.G?l.response:
l.responseText)||l.status>=400;if(m=g.SFa(l)){l=g.SN(a.B,a.policy,{});a.B.Ok(l,m);rhb(a,a.B);break a}n?a.player.oa("capfail",{status:l.status}):(a.player.Sh().Ag("fcb_r"),m=a.B.jb[0].Oa,a.W!=null&&a.L!==m&&(n=a.B.jb[0],a.G?a.W(l.response,(n.startTime+a.player.Nc())*1E3):a.W(l.responseText,(n.startTime+a.player.Nc())*1E3),a.L=m))}a.B=null;a.C=null}}).vl(function(l){a.B=null;
a.C=null;var m;a.player.oa("capfail",{rn:f,status:(m=l.xhr)==null?void 0:m.status})});
a.B=b;ohb(a.D,a.B.jb[0].Oa)},x3=function(a,b){g.eY.call(this,b);
this.B=a;this.K=b;this.C=null;this.L=!1;this.U=g.RD(this.K.V())&&!this.B.isManifestless},thb=function(a,b){var c=[],d;
for(d in a.B.j)if(a.B.j.hasOwnProperty(d)){var e=a.B.j[d];if(g.t1a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.K.V().N("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.ffb.get(e);q==null&&(q=shb[e]||shb[e.replace(/-/g,"_")],g.ffb.set(e,q));h=q||h}c.push(new g.oQ({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
uhb=function(a,b){return b!=null&&b in a.B.j?a.B.j[b]:null},vhb=function(a,b,c){var d=[],e;
for(e in a.B.j)if(a.B.j.hasOwnProperty(e)){var f=a.B.j[e];if(g.t1a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},y3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Ve);a.params.Ve&&Object.assign(r,a.params.Ve);Object.assign(r,c.Ve);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Ve=r;var t=q.Yi===1,u=[{J:"span",S:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],y,A,C;(l=l.eb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(A=y.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({J:"button",S:"caption-edit",Y:{tabindex:"0","aria-label":mhb()},X:[{J:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},X:[{J:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.S.call(this,{J:"div",S:"caption-window",Y:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},X:u});var F=
this;this.L=[];this.Fa=!1;this.B=a;this.La=this.Ma=null;this.playerWidth=f;this.playerHeight=h;this.W=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.Ac=c;this.ra=b;this.D=this.Ea("captions-text");this.Sb=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Va=whb(d,e,f,h);this.uc=m;l&&(this.G=this.Ea("caption-edit"),this.T(this.G,"click",function(){F.uc()}));
this.type=0;this.Ya=this.Va*xhb(r);this.Db=p;a=new g.DX(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.n5,this);a.subscribe("dragmove",this.m5,this);a.subscribe("dragend",this.l5,this);this.ib=this.bb=this.tb=this.rb=0;a="";this.j.windowOpacity&&(a=lhb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":yhb[this.j.textAlign]};this.Sb&&(b["border-radius"]=a?this.Ya/8+"px":"");(this.C=
this.B.params.Yi===2||this.B.params.Yi===3)&&zhb(this,this.element);g.ym(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Om){case 0:case 1:case 2:g.wp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.wp(this.element,"ytp-caption-window-bottom")}},zhb=function(a,b){var c="vertical-rl";
a.j.OU===1&&(c="vertical-lr");g.Am&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.ym(b,"-o-writing-mode",c);g.ym(b,"-webkit-writing-mode",c);g.ym(b,"writing-mode",c);g.ym(b,"text-orientation","upright");g.wp(b,"ytp-vertical-caption");a.B.params.Yi===3&&(g.ym(b,"text-orientation",""),g.ym(b,"transform","rotate(180deg)"))},xhb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},Ahb=function(a,b){var c={},d=b.background?b.background:a.j.Ve.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Ve.backgroundOpacity;d=lhb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Sb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ya/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Va*xhb(b)+"px";d=1;e=b.color||a.j.Ve.color;if(b.color||b.textOpacity!=null)e=lhb(e),d=b.textOpacity==null?a.j.Ve.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.hP&&(h=e=b.hP);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.fs()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Ve.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.I$&&(c.visibility="hidden");b.TZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.aQ||g.Kt,a.B.params.Yi===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.Ap===1||b.Ap===2||b.Ap===3||b.Ap===4||b.Ap===5)if(g.aQ)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ap){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},z3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},Bhb=function(a){a.W=g.jh("SPAN");
g.ym(a.W,{display:"block"});g.wp(a.W,"caption-visual-line");a.D.appendChild(a.W)},Chb=function(a,b){var c=g.jh("SPAN");
g.ym(c,{display:"inline-block","white-space":"pre-wrap"});g.ym(c,Ahb(a,b));c.classList.add("ytp-caption-segment");a.W.appendChild(c);c.previousElementSibling&&(g.ym(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ym(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Dhb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Ve);Object.assign(d,c||b.j);Object.assign(d,a.Ac.Ve);(c=!a.W)&&Bhb(a);for(var e=a.Ma&&a.La&&g.Ng(d,a.La)?a.Ma:Chb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(Bhb(a),e=Chb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.kh(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.aQ||!g.Bm(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Bm(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.fh?g.ym(e,m,"1em"):g.ym(e,m,"0.5em")))}a.La=d;a.Ma=e;a.L.push(b)},whb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},Fhb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new Ehb(this);this.G=new Ehb(this);this.j=[];this.clear()},$hb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{Ww:a,
Qt:b,result:0};a=Ghb[a];b=Ghb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Be()&&c.Qt===d;if(d)return{Ww:a,Qt:b,result:1}}else if(b&128&&1<=a&&a<=31)return{Ww:a,Qt:b,result:2};return{Ww:a,Qt:b,result:3}},bib=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,aib(a.D,b,c,d))},cib=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?bib(a,d.ZX,d.aY,b):d.type===1&&a.B&496&&aib(a.G,d.ZX,d.aY,b);a.j.length=0},A3=function(){this.type=0},B3=function(){this.state=this.Qt=this.Ww=0},dib=function(){this.timestamp=this.j=0},C3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new A3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new dib}},D3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},iib=function(a,b){switch(a){case 0:return eib[(b&127)-32];
case 1:return fib[b&15];case 2:return gib[b&31];case 3:return hib[b&31]}return 0},E3=function(a){return a.B[a.row][a.col]},F3=function(a,b,c){b>=2&&a.col>1&&(--a.col,E3(a).j=0);
var d=E3(a);d.timestamp=a.D.time+0;d.j=iib(b,c);a.col<32&&a.col++},jib=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},G3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},kib=function(a){a.row=a.j>0?a.j:1;
a.col=1;G3(a,0,15)},lib=function(a){this.C=a;
this.G=0;this.style=new A3;this.L=new C3(this.C);this.U=new C3(this.C);this.text=new C3(this.C);this.B=this.L;this.D=this.U;this.j=this.B},mib=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(D3(d,c),kib(a.B),kib(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(D3(d,c),G3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},nib=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},oib=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},Ehb=function(a){this.j=a;
this.G=0;this.C=new lib(this.j);this.L=new lib(this.j);this.B=new B3;this.D=this.C},aib=function(a,b,c,d){a.B.update();
b=$hb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ww;c=b.Qt;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&F3(a,0,b),c&96&&F3(a,0,c),b!==0&&c!==0&&a.style.type===3&&D3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Ww=e,b.Qt=c,b.state=2,b=e&8?a.L:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;jib(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));G3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:F3(b.j,0,32);break a;case 48:c===57?(d=b.j,E3(d).j=0,d.col<32&&d.col++):F3(b.j,1,c&15)}break;case 2:c&32&&F3(b.j,2,c&31);break;case 3:c&32&&F3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:nib(b);
break;case 33:d=b.j;d.col>1&&(--d.col,E3(d).j=0);break;case 36:d=b.j;b=E3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:mib(b,2,d);break;case 38:mib(b,3,d);break;case 39:mib(b,4,d);break;case 40:F3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);kib(d);oib(b);break;case 43:oib(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:D3(a,
d)}G3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;D3(a,d);jib(a,b,b+1,a.j-1);G3(a,a.row,1)}break;case 46:G3(b.D,0,15);break;case 47:D3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,nib(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},pib=function(){},H3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.wE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},rib=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.qg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=qib(l.textContent,n.textContent,p.textContent,f.textContent,h);return new H3(a,b,e,c,l,d,m)}switch(m.qg){case 9:case 10:m.Ap=1;break;case 11:m.Ap=2;break;case 12:m.Ap=3;break;case 13:m.Ap=4;break;case 14:m.Ap=5}return new H3(a,b,e,c,l.textContent||"",d,m)},qib=function(a,b,c,d,e){var f=g.fs(),h=
f?g.jh("DIV"):g.jh("RUBY"),l=g.jh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.jh("DIV"):g.jh("RP");a.textContent=b;h.appendChild(a);b=f?g.jh("DIV"):g.jh("RT");b.textContent=c;h.appendChild(b);c=e.qg;if(c===10||c===11||c===12||c===13||c===14)if(g.ym(b,"text-emphasis-style","filled circle"),g.ym(b,"text-emphasis-color","currentcolor"),g.ym(b,"webkit-text-emphasis","filled circle"),e.qg===11||e.qg===13)g.ym(b,"webkit-text-emphasis-position","under left"),g.ym(b,"text-emphasis-position","under left");c=!0;if(e.qg===4||e.qg===7||e.qg===12||
e.qg===14)g.ym(h,"ruby-position","over"),g.ym(h,"-webkit-ruby-position","before");else if(e.qg===5||e.qg===6||e.qg===11||e.qg===13)g.ym(h,"ruby-position","under"),g.ym(h,"-webkit-ruby-position","after"),c=!1;e=f?g.jh("DIV"):g.jh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ym(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ym(f,"display","none"),f=f.nextElementSibling,g.ym(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ym(h.lastElementChild,"display","none"),d?(g.ym(h,"padding-top","0.6em"),g.ym(f,"top","0")):(g.ym(h,"padding-bottom","0.6em"),g.ym(f,"bottom","0")));return h},I3=function(){g.O.apply(this,arguments)},J3=function(a,b,c,d,e){g.wE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},sib=function(a){var b="_"+K3++;
return new J3(0,0x8000000000000,0,b,a)},L3=function(a){I3.call(this);
this.C=a;this.pens={};this.U={};this.W={};this.D="_"+K3++;this.L={};this.B=this.j=null;this.G=!0},M3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},N3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},O3=function(a,b){a=M3(a,b);
return a!==void 0?a:null},Q3=function(a,b){a=a.getAttribute(b);
if(a!=null)return P3.test(a),a},tib=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.W[d]:a.C);a=O3(b,"mh");a!=null&&(c.LB=a);a=O3(b,"ju");a!=null&&(c.textAlign=a);a=O3(b,"pd");a!=null&&(c.Yi=a);a=O3(b,"sd");a!=null&&(c.OU=a);a=Q3(b,"wfc");a!=null&&(c.windowColor=a);b=M3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},uib=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.U[d]);a=O3(b,"ap");a!=null&&(c.Om=a);a=M3(b,"cc");a!=null&&(c.Tt=a);a=M3(b,"ah");a!=null&&(c.Tk=a);a=M3(b,"rc");a!=null&&(c.Ts=a);b=M3(b,"av");b!=null&&(c.Cp=b);return c},vib=function(a,b,c,d){var e={};
Object.assign(e,uib(a,b));Object.assign(e,tib(a,b));d?g.Ng(e,a.C)?(d=a.D,e=a.C):d="_"+K3++:d=b.getAttribute("id")||"_"+K3++;a=M3(b,"t")+c;b=M3(b,"d")||0x8000000000000;if(e.Yi===2||e.Yi===3)c=e.Ts,e.Ts=e.Tt,e.Tt=c;return new J3(a,b,0,d,e)},R3=function(a){I3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},S3=function(a){a=g.tg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-a.length)+a},wib=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Ts=a);b=b.ccColCount;b!==void 0&&(f.Tt=b);if(f.Yi===2||f.Yi===3)b=f.Ts,f.Ts=f.Tt,f.Tt=b;return new J3(c,d,0,e,f)},T3=function(a,b,c){g.eY.call(this,a);
this.videoData=b;this.audioTrack=c;this.G=b.Fw},U3=function(a,b,c,d,e,f,h,l,m,n){y3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},V3=function(a,b,c){this.trackData=a;
this.L=c;this.version=this.G=this.C=this.byteOffset=0;this.B=[];this.j=new DataView(this.trackData)},W3=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},X3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},Y3=function(a,b){I3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new Fhb;this.j.B=1<<this.track},yib=function(a){if(typeof a==="string")return!1;
a=new V3(a,8,0);return xib(a)},xib=function(a){if(!(a.byteOffset<a.j.byteLength)||X3(a)!==1380139777)return!1;
a.version=W3(a);if(a.version>1)return!1;W3(a);W3(a);W3(a);return!0},Z3=function(a,b,c,d,e,f,h,l,m,n){y3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ba=[];this.qa=this.Z=this.Pa=0;this.Da=NaN;this.Ib=0;this.Vb=null;this.Ua=new g.op(this.Lca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.DX(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.wp(this.element,"ytp-caption-window-rollup");g.P(this,this.Ua);g.ym(this.element,"overflow","hidden")},zib=function(a,b){if(!b)return"";
a.C&&a.B.params.OU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Aib=function(a){a.Ba=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Ts,c=0,d=0,e=a.Ba.length-1;c<b&&e>-1;){var f=a.Ba[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Z=d;b=Math;c=b.max;isNaN(a.Da)&&((d=a.j.Tt)?(e=g.jh("SPAN"),g.qh(e,"\u2013".repeat(d)),g.ym(e,Ahb(a,a.j.Ve)),a.D.appendChild(e),a.Da=e.offsetWidth,a.D.removeChild(e)):a.Da=0);d=a.D;a.qa=c.call(b,a.Da,a.Ib,(a.C?d.offsetHeight:d.offsetWidth)+1)},Bib=function(a,b){Aib(a);
var c=a.Ba.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Z-c;if(c!==a.Pa){var d=c>0&&a.Pa===0,e=c<a.Pa;b||isNaN(c)||d||!e||(g.wp(a.element,"ytp-rollup-mode"),g.pp(a.Ua));g.ym(a.D,"transform",zib(a,c));a.Pa=c}Aib(a)},$3=function(){I3.call(this)},Cib=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new H3(b,c,d,e.id,p.nodeValue,f||n>0,g.Lg(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Cib(a,b,c,d,e,!0,p,q,m)}}},Dib=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},Eib=function(a,b,c,d){d=Object.assign({LB:0},d);
return new J3(a,b,c,"_"+K3++,d)},a4=function(a,b){g.O.call(this);
this.K=a;this.ea=b;this.j=null;this.B=this.K.QA();this.logger=new g.GT("caps")},Fib=function(a){if(typeof a==="string"||yib(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.WM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.eB(a)},Hib=function(a,b,c){if(typeof b==="string"||yib(b))return[{trackData:b,
IU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.QEa(d);if(a.B&&e){var f=g.IEa(e),h=g.JEa(e);e=e.wj;f&&e&&a.B.xI(e,f,h)}a=g.eN(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.eB(e),f.push({trackData:e,IU:c+h*1E3});Gib(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Gib=function(a,b,c){var d=g.WM(a,0,1836476516),e=9E4;
d&&(e=g.XM(d)||9E4);d=0;for(var f=g.eN(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.WM(a,l.dataOffset,1953653094))&&(l=g.WM(a,l.dataOffset,1952867444))&&(l=g.cN(l)/e*1E3,h===0&&(d=l),b[h].IU=l-d+c||c*h*1E3)}},Iib=function(a,b,c,d,e){if(!yib(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new Y3(e,b));return a.j.kp(c,d)},Jib=function(a,b,c){a.j||(a.j=new $3);
a=a.j.kp(b,c);Math.random()<.01&&g.bx(Error("Deprecated subtitles format in web player: WebVTT"));return a},Lib=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new R3(Kib(b))),a.j.kp(c,d)}catch(f){return g.ax(f),[]}var e=g.j1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new L3(Kib(b),a.ea)),a.j.kp(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Kib=function(a){var b=
{};
if(a=g.rQ(a))b.lang=a,g.xcb.test(a)&&(b.Yi=1);return b},b4=function(a){g.cY.call(this,a);
var b=this;this.K=a;this.Fa=[];this.ra={};this.Va={};this.U=!1;this.B=this.j=this.W=this.Z=this.Pa=this.rb=null;this.ea=this.K.V();this.videoData=this.K.getVideoData();this.tb=this.K.qb();var c;this.ib=(c=this.K.getVideoData(1))==null?void 0:g.fR(c);this.C={Ve:{}};this.G={Ve:{}};this.Sb=g.KR(this.videoData);this.bb=g.u1a(this.videoData,this.K);this.Ib=!!this.videoData.captionTracks.length;this.Vb=!!this.videoData.nf;this.Ua=this.ea.controlsType==="3";this.Ya=new a4(this.K,this.ea);this.Ba=new g.ZF(this);
this.L=new g.S({J:"div",S:"ytp-caption-window-container",Y:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Zp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Qp(d));this.storage=c;var e;this.Kb=!((e=a.Le())==null||!e.oI());this.D=Mib(this);this.Da=!this.D&&this.Ua&&this.Kb&&this.bb;g.P(this,this.Ya);this.D?this.La=this.Ma=null:(this.Ma=new g.np(this.aV,void 0,this),g.P(this,this.Ma),this.La=new g.op(this.vea,2E3,this),g.P(this,
this.La));g.P(this,this.Ba);g.mS(this.player,this.L.element,4);g.P(this,this.L);this.D||this.Ba.T(a,"resize",this.dV);(this.Db=g.IP(this.ea)&&!g.Gs()&&!this.K.isFullscreen()&&!this.D&&!this.Da)&&this.Ba.T(a,"resize",this.Uba);this.Ba.T(a,"onPlaybackAudioChange",this.hba);this.Ba.T(a,g.yE("captions"),function(f){b.onCueRangeEnter(f)});
this.Ba.T(a,g.zE("captions"),function(f){b.onCueRangeExit(f)});
this.ib&&this.Ba.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
Nib(this,nhb()||{});this.player.Bd("onCaptionsModuleAvailable")},Qib=function(a){if(a.ea.Kb===1||a.videoData.vD===1||g.tR(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.ea.Kb===2){if(g.YP(a.ea))var c=Oib(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=ehb(a.player.getAudioTrack(),g.YP(a.ea));var d=g.tR(a.videoData,"yt:cc");if(Pib(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||
g.tR(a.videoData,"yt:cc")==="on"},c4=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},Pib=function(a){var b=void 0,c=g.dt(g.ct(),65);
if(g.YP(a.ea)&&c!=null){if(Oib(a)!=null)return!1;b=!c}return b},Rib=function(a){var b;
a.Sb?b=new T3(a.player,a.videoData,a.getAudioTrack()):a.bb?b=new x3(a.videoData.j,a.player):a.Ib?b=new g.fY(a.player,a.videoData,a.getAudioTrack()):b=new g.gY(a.player,a.videoData.nf,a.videoData.videoId,g.YMa(a.videoData),a.videoData.Vn,a.videoData.eventId);return b},e4=function(a,b){if(!a.j)return null;
if(a.W&&a.W.D)return a.W.D;b=Sib(a,b);b=g.SX(a.j.j,b);var c=null;if(fhb(a.ea)){var d=a.K.isInline()?void 0:g.Xs("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.ea.captionsLanguagePreference,g.tR(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.rQ(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.rQ(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,e.length))for(e=g.w(e),
f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.ea.captionsLanguagePreference,g.tR(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.rQ(b[f])===d[e])return b[f];d=null;a.W&&a.W.C&&(d=a.W.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||d4(a));d&&c&&g.rQ(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=ghb(d,c));return d},d4=function(a){return a.W&&a.W.j},f4=function(a){var b=d4(a);
return!!b&&a.B===b},Tib=function(a){var b=ehb(a.player.getAudioTrack(),g.YP(a.ea));
var c=b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?e4(a,a.U):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&c4(a)?d4(a):Pib(a)||a.U||Qib(a)?e4(a,a.U):c4(a)?d4(a):null;if(a.D||a.Da){var d=g.SX(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.jh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.pQ(f));h.setAttribute("srclang",g.rQ(f));h.setAttribute("id",f.toString());a.Da||h.setAttribute("src",a.j.Fx(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.K.Le();c.EE(b);b=
c.Jb();a.Kb&&a.Ba.T(b.textTracks,"change",a.uda)}else!a.B&&c&&g4(a,c),a.player.Bd("onCaptionsTrackListChanged"),a.player.xf("onApiChange")},Uib=function(a,b){var c=a.K.Le().Jb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},g4=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.U=c,a.U&&(g.YP(a.ea)?h4(a,!!b):i4(a,!!b)));a.ea.N("html5_report_caption_format_change")&&Vib(a,a.B,b,a.U,!1);a.B=b;c4(a)&&(b=d4(a),a.ea.N("html5_report_caption_format_change")&&Vib(a,a.B,b,a.U,!0),a.B=b);var d;Wib(a,(d=a.B)!=null?d:void 0);a.load()},Yib=function(a,b){if(b instanceof J3){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=Xib(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},Xib=function(a,b){var c=Zib(a);
if(!c)return null;var d=a.B?g.rQ(a.B):null;d&&g.xcb.test(d)&&(b.params.Yi=1);var e=a.tb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.ea.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.LB!=null?b.params.LB:b.j.length>1?1:0){case 1:return new U3(b,a.C,a.G,c.width,c.height,e,d,a.ea.experiments,a.TN.bind(a),a.K);case 2:return new Z3(b,a.C,a.G,c.width,c.height,e,d,a.ea.experiments,a.TN.bind(a),a.K);default:return new y3(b,a.C,a.G,c.width,c.height,
e,d,a.ea.experiments,a.TN.bind(a),a.K)}},Nib=function(a,b,c){c=c===void 0?!1:c;
var d=j4.Ve;a.C={};Object.assign(a.C,j4);a.C.Ve={};Object.assign(a.C.Ve,d);a.G={Ve:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;P3.test(f);e.Ve.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;P3.test(f);e.Ve.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||j4.windowColor;P3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Ve.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Ve.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Ve;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Ve.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=j4.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Ve.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Ve.fontFamily=f;a.loaded&&a.dV();c&&g.Ws("yt-player-caption-display-settings",b,2592E3)},$ib=function(a,b){if(!a.j)return{};
if(b){a.ea.N("html5_report_caption_format_intent")&&!g.Lg(b)&&a.il(b.vss_id,"m");if(a.D||!g.Ta(b))return;if(g.Lg(b)){g4(a,null,!0);return}for(var c,d=g.SX(a.j.j,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&(f.languageName!==b.languageName||(f.captionId||"")!==(b.captionId||"")||g.pQ(f)!==b.displayName)||(c=b.translationLanguage?ghb(f,b.translationLanguage):f)}a.FN(b.position);!c||c===a.B&&a.loaded||(b=g.WL(),d=g.rQ(c),b.length&&d===b[b.length-1]||(b.push(d),g.Ws("yt-player-caption-language-preferences",
b)),fhb(a.ea)&&!a.K.isInline()&&g.Ws("yt-player-caption-sticky-language",d,2592E3),g4(a,c,!0))}else return a.loaded&&a.B&&!f4(a)?g.qQ(a.B):{};return""},bjb=function(a,b,c){b&&!a.Z?(b=sib({Yi:0,
lang:"en"}),a.Z=[b,new H3(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.df(a.Z)):!b&&a.Z&&(ajb(a,a.Z),a.Z=null)},ajb=function(a,b){a.player.ll(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Xb(a.Fa,c.value);v3(a.Ma)},Wib=function(a,b){a.ea.N("html5_modify_caption_vss_logging")&&(a.videoData.nE=b)},Zib=function(a){var b=a.tb.getVideoContentRect(!0).height,c=a.tb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},i4=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},h4=function(a,b){a.K.isInline()||g.Ws("yt-player-sticky-caption",b,2592E3)},Oib=function(a){if(!a.K.isInline())return g.Xs("yt-player-sticky-caption")},Mib=function(a){var b,c=!((b=a.K.Le())==null||!b.nI());
return a.Ua&&c&&!a.bb},Sib=function(a,b){g.FR(a.videoData)&&(b=!0);
b||(b=a.Vb?!1:a.Ib?!1:!0);return b||a.ea.N("web_deprecate_always_includes_asr_setting")&&g.YP(a.ea)?!0:!!g.dt(g.ct(),66)},Vib=function(a,b,c,d,e){e?a.uj(c,!0,"g"):d?b?a.uj(c,!!c,"m"):c&&a.uj(c,!0,"m"):!b&&c&&a.uj(c,!0,"s")};
g.eY.prototype.yT=g.ca(55,function(){return!1});
g.eY.prototype.Uu=g.ca(54,function(){});
g.fY.prototype.Uu=g.ca(53,function(a,b,c){var d=this;this.Ja();b=this.Fx(a,b);var e=this.Qa.V().N("html5_report_captions_ctmp_qoe"),f=(0,g.St)();this.zt();dhb(this,b,{format:"RAW",onSuccess:function(h){d.B=null;if(e){var l=(h.responseText.length/1024).toFixed(),m=(0,g.St)();d.videoData.oa("capresp",{ms:m-f,kb:l})}c(h.responseText,a)},
onError:e?function(h){var l;h=(l=h==null?void 0:h.status)!=null?l:0;d.videoData.oa("capfail",{status:h})}:void 0,
withCredentials:!0})});
g.gY.prototype.Uu=g.ca(52,function(a,b,c){var d=this;this.Ja();b=this.Fx(a,b);this.zt();this.B=g.Or(b,{format:"RAW",onSuccess:function(e){d.B=null;c(e.responseText,a)},
withCredentials:!0})});
g.LX.prototype.mA=g.ca(51,function(){for(var a=g.ch(document,"track",void 0,this.j),b=0;b<a.length;b++)g.oh(a[b])});
g.i_.prototype.mA=g.ca(50,function(){this.mediaElement.mA()});
g.LX.prototype.oI=g.ca(49,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.i_.prototype.oI=g.ca(48,function(){return this.mediaElement.oI()});
g.LX.prototype.nI=g.ca(47,function(){return!!this.j.textTracks});
g.i_.prototype.nI=g.ca(46,function(){return this.mediaElement.nI()});
g.LX.prototype.EE=g.ca(45,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.i_.prototype.EE=g.ca(44,function(a){this.mediaElement.EE(a)});
g.LV.prototype.xI=g.ca(40,function(a,b,c){this.fd.xI(a,b,c)});
g.r_.prototype.xI=g.ca(39,function(a,b,c){this.Ma.set(a,{Yt:b,Zz:c})});
g.LV.prototype.GF=g.ca(38,function(a){return this.fd.GF(a)});
g.r_.prototype.GF=g.ca(37,function(a){var b=2;this.L.has(a)?b=0:g.c7a(this,a)&&(b=1);return b});
g.GT.prototype.j=g.ca(36,function(a){g.sPa.apply(null,[6,this.tag,a].concat(g.x(g.Ea.apply(1,arguments))))});
g.fS.prototype.il=g.ca(34,function(a,b){var c=g.$R(this.app);c&&c.il(a,b)});
g.cW.prototype.il=g.ca(33,function(a,b){a=[a,b];g.bW(this,g.FK(this.provider),"cfi",a)});
g.qW.prototype.il=g.ca(32,function(a,b){this.qoe&&this.qoe.il(a,b)});
g.RW.prototype.il=g.ca(31,function(a,b){this.Wb().il(a,b)});
g.fS.prototype.uj=g.ca(30,function(a,b,c){var d=g.$R(this.app);d&&d.uj(a,b,c)});
g.cW.prototype.uj=g.ca(29,function(a,b,c){b=[a,b,this.Vb,c];g.bW(this,g.FK(this.provider),"cfs",b);this.Vb=a});
g.qW.prototype.uj=g.ca(28,function(a,b,c){this.qoe&&this.qoe.uj(a,b,c)});
g.RW.prototype.uj=g.ca(27,function(a,b,c){this.Wb().uj(a,b,c)});
g.GV.prototype.UF=g.ca(18,function(){return this.U});
g.P_.prototype.UF=g.ca(17,function(){var a;return((a=g.$R(this))==null?void 0:a.QA())||null});
g.fS.prototype.QA=g.ca(16,function(){return this.app.UF()});
g.RW.prototype.QA=g.ca(15,function(){var a;return((a=this.va)==null?void 0:a.UF())||null});
g.IM.prototype.FK=g.ca(1,function(a){return(a=this.Fo(a))?a.j:0});
g.hO.prototype.FK=g.ca(0,function(){return 0});
var khb=/#(.)(.)(.)/,jhb=/^#(?:[0-9a-f]{3}){1,2}$/i,shb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};w3.prototype.contains=function(a){a=g.ec(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
w3.prototype.length=function(){return this.segments.length/2};
g.z(phb,g.O);g.k=phb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.VB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Nc();var b=this.j;this.j=g.Qb(this.qa.Yr(a).jb);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.D=new w3;this.L=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.M_=function(){this.Ja();var a;if(a=this.j!=null)a=this.j,a=a.j.Jt(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.LD(a);var b=a.jb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.QA()){var d=b.j.info.id,e=b.Oa,f=a.jb[0].bf;if(this.policy.La){if(c=c.IK(f,e,d,3))a.D=c}else if(d=c.IA(f,e,d,3))if(c=c.GF(e),c===0)d&&(a.j=new g.AM(d));else if(c===2){this.U.start();qhb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Po(b.Oa)?(this.D.contains(a.jb[0].Oa)||rhb(this,a),this.j=g.Qb(a.jb)):qhb(this)&&this.seekTo(this.player.getCurrentTime())}this.U.start()};
g.z(x3,g.eY);g.k=x3.prototype;g.k.Uu=function(a,b,c){var d=this;this.zt();b=uhb(this,a.getId());b||(b=a.languageCode,b=this.B.isManifestless?vhb(this,b,"386"):vhb(this,b));if(b){var e=(b.index.FK(b.index.Io())-b.index.getStartTime(b.index.Io()))*1E3,f=this.K.V(),h=new g.ySa(f),l=function(){d.C&&d.C.reset();d.L=!0};
f.N("html5_keep_caption_data_after_seek")&&(l=null);this.C=new phb(h,this.K,b,function(m,n){c(m,a,n,e)},this.U||g.mG(b.info),l)}};
g.k.yT=function(){var a=this.L;this.L=!1;return a};
g.k.AB=function(a){var b=this.U?[new g.oQ({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.oQ({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.B.isManifestless?thb(this,"386"):thb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.dY(this.j,c.value);a()};
g.k.zt=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Fx=function(){return""};
g.k.EH=function(){this.C&&(this.C.reset(),this.K.Ze("captions"))};
var P3=/^#(?:[0-9a-f]{3}){1,2}$/i;var yhb=["left","right","center","justify"];g.z(y3,g.S);g.k=y3.prototype;g.k.n5=function(a,b){this.bb=a;this.ib=b;var c=g.Im(this.element,this.element.parentElement);this.rb=a-c.x;this.tb=b-c.y};
g.k.m5=function(a,b){if(a!==this.bb||b!==this.ib){g.vp(this.element,"ytp-dragging")||g.wp(this.element,"ytp-dragging");var c=g.Km(this.element);a=a-this.rb-.02*this.playerWidth;var d=b-this.tb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.tg(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.tg(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.tg(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.tg(c,0,1)*100;this.B.params.Om=b;this.B.params.Cp=c;this.B.params.Tk=
a;this.B.params.isDefault=!1;this.j.Om=b;this.j.Cp=c;this.j.Tk=a;this.j.isDefault=!1;this.ra.Om=b;this.ra.Cp=c;this.ra.Tk=a;this.ra.isDefault=!1;this.o2()}};
g.k.l5=function(){g.yp(this.element,"ytp-dragging")};
g.k.o2=function(){this.KC(this.L)};
g.k.getType=function(){return this.type};
g.k.KC=function(a){var b=this.Db?0:Math.min(this.aZ(),this.maxWidth),c=this.ZY(),d=this.Db;if(d){var e=getComputedStyle(this.D.parentNode);e=z3(e.borderLeftWidth)+z3(e.borderRightWidth)+z3(e.paddingLeft)+z3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Yi===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.ym(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.OO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Tk*.96+2;h=this.j.Om;switch(h){case 0:case 3:case 6:(d=this.j.Ve.fontSizeIncrement)&&d>0&&this.j.Yi!==2&&this.j.Yi!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.Cp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.ym(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.OO=function(a){var b;for(b=0;b<a.length&&a[b]===this.L[b];b++);if(this.Fa||this.L.length>b)b=0,this.Fa=!1,this.L=[],this.W=this.La=this.Ma=null,g.mh(this.D);for(;b<a.length;b++)Dhb(this,a[b])};
g.k.aZ=function(){return 0};
g.k.ZY=function(){return 0};
g.k.toString=function(){return g.S.prototype.toString.call(this)};Fhb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
Fhb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var Ghb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];A3.prototype.set=function(a){this.type=a};
A3.prototype.get=function(){return this.type};
B3.prototype.clear=function(){this.state=0};
B3.prototype.update=function(){this.state=this.state===2?1:0};
B3.prototype.Be=function(){return this.state!==0};
B3.prototype.matches=function(a,b){return this.Be()&&a===this.Ww&&b===this.Qt};
dib.prototype.reset=function(){this.timestamp=this.j=0};
C3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
C3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
C3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var eib=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],fib=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],gib=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],hib=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];lib.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.L;this.D=this.U;this.j=this.B;var c=(a<<2)+(b<<1);this.L.reset(c);this.U.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Ehb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.L.reset(a,1)};pib.prototype.D=function(){};g.z(H3,g.wE);H3.prototype.toString=function(){return g.wE.prototype.toString.call(this)};g.z(I3,g.O);I3.prototype.kp=function(){return[]};
I3.prototype.reset=function(){};g.z(J3,g.wE);J3.prototype.toString=function(){return g.wE.prototype.toString.call(this)};
var K3=0;g.z(L3,I3);L3.prototype.reset=function(){this.L={};this.B=this.j=null;this.G=!0};
L3.prototype.kp=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=N3(a,"b");
l!=null&&(h.bold=l);l=N3(a,"i");l!=null&&(h.italic=l);l=N3(a,"u");l!=null&&(h.underline=l);l=O3(a,"et");l!=null&&(h.charEdgeStyle=l);l=O3(a,"of");l!=null&&(h.offset=l);l=Q3(a,"bc");l!=null&&(h.background=l);l=Q3(a,"ec");l!=null&&(h.hP=l);l=Q3(a,"fc");l!=null&&(h.color=l);l=O3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=M3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=M3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=M3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=O3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.qg=l>10?l-1:l);a=O3(a,"hg");a!=null&&(h.TZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.W[c]=tib(this,a);break;case "wp":c=a.getAttribute("id"),this.U[c]=uib(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=vib(this,a,b,!1);(a=this.L[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.L[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!N3(m,"a");l=(M3(m,"t")||0)+l;var n=M3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.qg&&(t.qg===1?(t=r.slice(m,
m+4),t.length===4&&(u=rib(l,n,f,h,p,t,this.pens),m+=3)):u=rib(l,n,f,h,p,[y],this.pens)),!u){var A=y;u=l;y=n;t=f;var C=h,F=p,H=A.textContent?A.textContent:"",K=A.getAttribute("p");K=K?this.pens[K]:null;A=M3(A,"t")||0;u=new H3(u+A,y-A,F,t,H,C,K)}}else u=new H3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=vib(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var cjb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(R3,I3);R3.prototype.reset=function(){this.B.clear()};
R3.prototype.kp=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.hP=S3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=S3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=S3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.qg=h>10?h-1:h,f.Ap=cjb.get(f.qg));e.hgHorizGroup&&(f.TZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.LB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Yi=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.OU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=S3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Tk=e.ahHorPos),e.apPoint!==void 0&&(f.Om=e.apPoint),e.avVerPos!==void 0&&(f.Cp=e.avVerPos),e.ccCols!==void 0&&(f.Tt=e.ccCols),e.rcRows!==void 0&&(f.Ts=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=wib(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+K3++,d=wib(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.LB!=null?l.params.LB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],F;if(F=A&&A.qg===1){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var K=F[H+1].pPenId;(K=this.j.get(K))&&K.qg&&K.qg===2?(K=F[H+2].pPenId,K=this.j.get(K),!K||!K.qg||
K.qg<3?F=!1:(K=F[H+3].pPenId,F=(K=this.j.get(K))&&K.qg&&K.qg===2?!0:!1)):F=!1}}if(F)y=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=qib(u,y,F,t,H),t=new H3(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var N=void 0;C=A;F=r;H=e;K=f;var W=y,V=p,da=n,na=[],X=g.j1("<html>"+u+"</html>");if(!X.getElementsByTagName("parsererror").length&&((N=X.firstChild)==null?0:N.childNodes.length))for(N=g.w(X.firstChild.childNodes),X=N.next();!X.done;X=N.next()){X=X.value;var R=void 0,Y=void 0,
v=(Y=(R=X.textContent)==null?void 0:R.replace(/\n/g,""))!=null?Y:"";if(X.nodeType!==3||v&&v.match(/^ *$/)==null){R={};Object.assign(R,C||F);Y=void 0;switch((Y=X)==null?void 0:Y.tagName){case "b":R.bold=!0;break;case "i":R.italic=!0;break;case "u":R.underline=!0}na.push(new H3(H+W,K-W,V,l.id,v,da,R))}}C=na}C.length||(C=[new H3(e+y,f-y,p,l.id,u,n,A||r)])}if(C.length)for(n=g.w(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=[];return b};g.z(T3,g.eY);T3.prototype.Uu=function(a,b,c){ihb(this.videoData.videoId,a.vssId,c)};
T3.prototype.AB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.dY(this.j,c.value);a()};g.z(U3,y3);U3.prototype.OO=function(a){var b=this.B.j;y3.prototype.OO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,djb);var e=c.j;var f=d}Dhb(this,c,d)}};
var djb={I$:!0};g.z(V3,pib);V3.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+K3++;c=c/1E3-this.L;d=d/1E3-this.L;a=new J3(c,d-c,5,f,{textAlign:0,Om:0,Tk:b*2.5,Cp:a*5.33});e=new H3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(Y3,I3);Y3.prototype.kp=function(a){a=new V3(a,a.byteLength,this.B);if(xib(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=X3(a)*(1E3/45):a.version===1&&(a.C=X3(a)*4294967296+X3(a)),a.G=W3(a);a.G>0;a.G--){var b=W3(a),c=W3(a),d=W3(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,ZX:c,aY:d,order:b.j.length}))}cib(this.j,a);return a.B}return[]};
Y3.prototype.reset=function(){this.j.clear()};g.z(Z3,y3);g.k=Z3.prototype;g.k.o2=function(){g.qp(this.Ua)};
g.k.Lca=function(){g.yp(this.element,"ytp-rollup-mode");this.KC(this.Vb,!0)};
g.k.ZY=function(){return this.C?this.qa:this.Z};
g.k.aZ=function(){return this.C?this.Z:this.qa};
g.k.KC=function(a,b){this.Vb=a;if(this.B.params.Ts){for(var c=0,d=0;d<this.L.length&&c<a.length;d++)this.L[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.L.concat(a.slice(c)));this.Ib=this.qa;this.Z=this.qa=0;y3.prototype.KC.call(this,a);Bib(this,b)}y3.prototype.KC.call(this,a)};g.z($3,I3);
$3.prototype.kp=function(a,b){var c=[];a=a.split(ejb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!fjb.test(e)){var h=gjb.exec(e);if(h&&h.length>=4){var l=Dib(h[1]),m=Dib(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.Cp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Tk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Tk=0;break;case 1:h.Tk=100;break;case 2:h.Tk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Om=q}e=e.substring(gjb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=Eib(l,m,5,t),m=new H3(l,m,5,f.id,h,!1,g.Lg(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(hjb),q.length===1?(h=5,t=Eib(l,m,h,t)):(p=h=6,t=Object.assign({Tt:32},t),t=new J3(l,m,p,"_"+K3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.j1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,Cib(this,p,m-(p-l),h,t,r>0,y,e,c)):p=Dib(n)+f}gjb.lastIndex=0}}return c};
var fjb=/^NOTE/,ejb=/(?:\r\n|\r|\n){2,}/,gjb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),hjb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.j_.eL($3,{kp:"wvppt"});g.z(a4,g.O);
a4.prototype.kp=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a||this.ea.N("html5_use_subfragcaps_parser_for_all_live")){a:{var e=d,f=Hib(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.IU;h=typeof p!=="string"?h.concat(Iib(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(Jib(this,p,q)):h.concat(Lib(this,b,p,q))}var r=h;break a}catch(y){this.logger.j(187101178,"SS caps parsing failure fallback: "+y.message+". ");this.clear();r=null;break a}r=void 0}if(r!==
null&&r.length!==0)return r;if(this.ea.N("html5_disable_subfragcaps_fallback"))return[];r===null?(r=this.logger,g.vPa(r.tag,5,"SS caps fallback due to parse failure.",r.B)):this.logger.info("SS caps fallback due to no data received.")}a:if(a=Fib(a)){try{var t=typeof a!=="string"?Iib(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?Jib(this,a,c):Lib(this,b,a,c);break a}catch(y){if(this.ea.N("html5_report_captions_ctmp_qoe")){var u;this.K.oa("capprs",{e:(u=y)==null?void 0:u.message})}this.clear();t=[];break a}t=
void 0}else t=[];return t};
a4.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
a4.prototype.reset=function(){this.j&&this.j.reset()};
a4.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var j4={windowColor:"#080808",windowOpacity:0,textAlign:2,Om:7,Tk:50,Cp:100,isDefault:!0,Ve:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(b4,g.cY);g.k=b4.prototype;g.k.xa=function(){if(this.D||this.Da){var a=this.K.Le();a&&!a.Ja()&&a.mA()}else bjb(this,!1);g.cY.prototype.xa.call(this)};
g.k.uU=function(){return this.ea.N("html5_honor_caption_availabilities_in_audio_track")&&!this.bb};
g.k.Mv=function(){if(this.Ua)return this.D||this.Da;var a=this.getAudioTrack();if(this.uU()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=ehb(a,g.YP(this.ea));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?c4(this):Pib(this)||c4(this)?!0:Qib(this)};
g.k.load=function(){var a=this;g.cY.prototype.load.call(this);this.W=this.getAudioTrack();this.j?this.B&&(this.Ya.clear(),this.D?Uib(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Uu(this.B,"json3",function(b,c,d,e){if(b){var f;Wib(a,(f=a.B)!=null?f:void 0);a.j.yT()&&(a.Fa=[],a.K.Ze("captions"),v3(a.Ma),a.Ya.reset());if(a.videoData.Fd){var h;d=((h=d)!=null?h:0)+a.videoData.Fd}b=a.Ya.kp(b,c,d,e);if(a.ib)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.mm=a.videoData.Fd;c=!a.ea.N("html5_keep_caption_data_after_seek")&&a.bb;a.player.df(b,void 0,c);!a.U||a.Da||f4(a)||!a.ea.Tn||g.TD(a.ea)||g.KP(a.ea)||g.gz(a.ea)||a.ea.Ma==="shortspage"||a.player.isInline()||(g.rp(a.La),b=sib({Om:0,Tk:5,Cp:5,Ts:2,textAlign:0,Yi:0,lang:"en"}),a.Pa=[b],c=["Click "," for settings"],a.rb||(e=new g.Fx(g.Yx()),g.P(a,e),a.rb=e.element),e=b.end-b.start,(f=g.pQ(a.B))&&a.Pa.push(new H3(b.start,e,0,b.id,f)),a.Pa.push(new H3(b.start,e,0,b.id,c[0]),new H3(b.start,e,0,b.id,a.rb,
!0),new H3(b.start,e,0,b.id,c[1],!0)),a.player.df(a.Pa),g.pp(a.La));!a.U||a.Da||f4(a)||(g.YP(a.ea)?h4(a,!0):i4(a,!0),a.W&&(a.W.D=a.B),a.player.Gp());a.U=!1}}),this.D||this.Da||f4(this)||this.player.Bd("captionschanged",g.qQ(this.B))):(this.j=Rib(this),g.P(this,this.j),this.j.AB(function(){Tib(a)}))};
g.k.unload=function(){this.D&&this.B?Uib(this,!1):(this.La&&g.rp(this.La),this.player.Ze("captions"),this.Fa=[],this.j&&this.j.zt(),this.Ya.clear(),this.Z&&this.player.df(this.Z),this.dV());g.cY.prototype.unload.call(this);this.player.Gp();this.player.Bd("captionschanged",{})};
g.k.create=function(){this.Mv()&&this.load();var a;a:{var b,c,d;if(this.ea.N("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.K.publish("showpromotooltip",this.L.element)};
g.k.uda=function(){for(var a=this.K.Le().Jb().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.SX(this.j.j,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&g4(this,b,!0)};
g.k.aga=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);v3(this.Ma)};
g.k.onCueRangeExit=function(a){g.Xb(this.Fa,a);this.j instanceof x3&&this.j.U&&this.player.ll([a]);v3(this.Ma)};
g.k.getCaptionWindowContainerId=function(){return this.L.element.id};
g.k.vea=function(){ajb(this,this.Pa);this.Pa=null};
g.k.aV=function(){var a=this;if(!this.Db||!this.D){this.Ma.stop();g.sea(this.Va);this.Fa.sort(g.xE);var b=this.Fa;if(this.Z){var c=g.un(b,function(f){return this.Z.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())Yib(this,c.value);b=g.w(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={eB:void 0,Yp:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.eB=d;c.Yp=e;this.Va[c.eB]?(c.Yp.element.parentNode||(c.Yp instanceof Z3||c.Yp instanceof U3||g.Eg(this.ra,function(f){return function(h,l){l!==f.eB&&h.B.params.Om===f.Yp.B.params.Om&&h.B.params.Tk===f.Yp.B.params.Tk&&h.B.params.Cp===f.Yp.B.params.Cp&&(h.dispose(),delete a.ra[l]);
return l===f.eB}}(c),this),this.L.element.appendChild(c.Yp.element)),c.Yp.KC(this.Va[c.eB])):(c.Yp.dispose(),delete this.ra[c.eB])}}};
g.k.Cea=function(){Nib(this,{},!0);this.player.Bd("captionssettingschanged")};
g.k.U9=function(){var a=j4.Ve;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:j4.windowColor,windowOpacity:j4.windowOpacity};var b=nhb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.Y3=function(a,b){var c={};Object.assign(c,nhb());Object.assign(c,a);Nib(this,c,b);this.player.Bd("captionssettingschanged")};
g.k.dV=function(){!this.D&&this.loaded&&(g.Bg(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.aV())};
g.k.oi=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;a=g.tg(b,-2,4);this.Y3({fontSizeIncrement:a});return a;case "reload":b&&!this.D&&g4(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.ea.U&&(g.YP(this.ea)?h4(this,!!b):i4(this,!!b));break;case "track":return $ib(this,b);case "tracklist":return this.j?g.Jl(g.SX(this.j.j,!(!b||!b.includeAsr)),function(c){return g.qQ(c)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(c){return Object.assign({},c)}):[];
case "sampleSubtitles":this.D||b===void 0||bjb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||bjb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.WL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.W:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.ea.U&&a.push("stickyLoading");return a};
g.k.Zr=function(){var a=this.B;if(this.K.RK("captions")){if(this.ea.N("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.nE)!=null?b:null)?{cc:g.VKa(a)}:{}}if(a)return b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.rQ(a)),{cc:b}}return{}};
g.k.Nfa=function(){this.isSubtitlesOn()?(g.YP(this.ea)?h4(this,!1):i4(this,!1),Wib(this),this.ea.N("html5_report_caption_format_change")?g4(this,null,!0):(this.unload(),c4(this,!0)&&g4(this,d4(this),!1))):this.A3()};
g.k.A3=function(){var a=f4(this)||!this.B?e4(this,!0):this.B;this.ea.N("html5_report_caption_format_intent")&&a&&this.il(a.vssId,"m");this.isSubtitlesOn()||g4(this,f4(this)||!this.B?e4(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!f4(this)};
g.k.hba=function(){var a=f4(this);c4(this,a)?g4(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.uU()&&(this.U=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Mv()&&(a?g4(this,e4(this),!1):this.load()))};
g.k.FN=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.L.element.style.top=this.qa.top*100+"%",this.L.element.style.left=this.qa.left*100+"%",this.L.element.style.width=this.qa.width*100+"%",this.L.element.style.height=this.qa.height*100+"%",this.L.element.style.position="absolute",a=Zib(this))&&(this.L.element.style.width=a.width+"px",this.L.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.U=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Bd("captionschanged",{})),this.Mv()&&this.load())};
g.k.getAudioTrack=function(){return this.ib&&this.player.getPresentingPlayerType()===2?this.videoData.Al:this.player.getAudioTrack()};
g.k.Uba=function(){var a=this.K.Le();a&&!a.Ja()&&a.mA();this.K.isFullscreen()?(this.D=this.Ua=!0,this.loaded&&Tib(this)):(this.Ua=this.ea.controlsType==="3",this.D=Mib(this));g4(this,this.B)};
g.k.TN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.gb("innertubeCommand",d)};
g.k.uj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"");a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.K.uj(b?e:"",b?f:"",c)};
g.k.il=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.K.il(a,b)};
g.k.EH=function(){this.j instanceof x3&&this.j.EH()};
g.j_.eL(b4,{aV:"smucd"});g.bY("captions",b4);})(_yt_player);
